# Build settings

markdown: kramdown
permalink: none
plugins:             [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

port: 4000

sass:
  sass_dir: assets/css
  style: :nested

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		           "玲瑋珍錢幣古玩"
fulltitle:           "玲瑋珍錢幣古玩,Ling Wei Zhen Trading"
description:	       "Collectibles shop selling old Singapore and Chinese coins, banknotes, fine jade carvings, chinese antique porcelains, bronze wares, at Temple Street, Chinatown. "
author:              "Ling Wei Zhen"
